import { logger } from '../utils/logger'
import type { WikiPage, PageMeta, LogEntry, WikiTreeNode, RawFileInfo } from '../../types'

const WIKI_BASE = 'wiki'
const RAW_BASE = 'raw'
const QUERY_BASE = 'query'

interface FileOps {
  readFile(path: string): Promise<string>
  writeFile(path: string, content: string): Promise<void>
  listDir(path: string): Promise<string[]>
  createDir(path: string): Promise<void>
  fileExists(path: string): Promise<boolean>
  deleteFile?(path: string): Promise<void>
  deleteDir?(path: string): Promise<void>
}

export class WikiManager {
  private fileOps: FileOps
  private basePath: string

  constructor(fileOps: FileOps, basePath = WIKI_BASE) {
    this.fileOps = fileOps
    this.basePath = basePath
  }

  private resolvePath(subpath: string): string {
    return `${this.basePath}/${subpath}`
  }

  private resolveRaw(subpath: string): string {
    return `${RAW_BASE}/${subpath}`
  }

  private resolveQuery(subpath: string): string {
    return `${QUERY_BASE}/${subpath}`
  }

  async init(): Promise<void> {
    const wikiDirs = ['', 'pages']
    for (const dir of wikiDirs) {
      const fullPath = this.resolvePath(dir)
      if (!(await this.fileOps.fileExists(fullPath))) {
        await this.fileOps.createDir(fullPath)
        logger.info('WikiManager', `Created directory: ${fullPath}`)
      }
    }

    const rawDirs = ['pdfs', 'meetings', 'audio', 'chat', 'code', 'data', 'other']
    for (const dir of rawDirs) {
      const fullPath = this.resolveRaw(dir)
      if (!(await this.fileOps.fileExists(fullPath))) {
        await this.fileOps.createDir(fullPath)
        logger.info('WikiManager', `Created directory: ${fullPath}`)
      }
    }

    const queryDirs = ['plans', 'outputs']
    for (const dir of queryDirs) {
      const fullPath = this.resolveQuery(dir)
      if (!(await this.fileOps.fileExists(fullPath))) {
        await this.fileOps.createDir(fullPath)
        logger.info('WikiManager', `Created directory: ${fullPath}`)
      }
    }

    const indexMd = this.resolvePath('index.md')
    if (!(await this.fileOps.fileExists(indexMd))) {
      await this.fileOps.writeFile(indexMd, this.generateInitialIndex())
    }
    const logMd = this.resolvePath('log.md')
    if (!(await this.fileOps.fileExists(logMd))) {
      await this.fileOps.writeFile(logMd, '# Wiki Log\n\n')
    }
    logger.info('WikiManager', 'Wiki initialized with raw/wiki/query structure')
  }

  private generateInitialIndex(): string {
    return `# Wiki Index

Last updated: ${new Date().toISOString()}

## Pages

*No wiki pages yet*

---
*Generated by LLM Wiki Engine*
`
  }

  async readPage(path: string): Promise<WikiPage | null> {
    try {
      const fullPath = path.startsWith('wiki/') ? path : this.resolvePath(path)
      const content = await this.fileOps.readFile(fullPath)
      const meta = this.parseMeta(content, path)
      return { meta, content }
    } catch {
      return null
    }
  }

  async writePage(path: string, content: string): Promise<void> {
    const fullPath = path.startsWith('wiki/') ? path : this.resolvePath(path)
    await this.fileOps.writeFile(fullPath, content)
    logger.info('WikiManager', `Written page: ${path}`)
  }

  async deletePage(path: string): Promise<void> {
    const fullPath = path.startsWith('wiki/') ? path : this.resolvePath(path)
    if (this.fileOps.deleteFile) {
      await this.fileOps.deleteFile(fullPath)
    } else {
      await this.fileOps.writeFile(fullPath, '')
    }
    logger.info('WikiManager', `Deleted page: ${path}`)
  }

  async listPages(): Promise<string[]> {
    const searchPath = this.resolvePath('pages')
    const entries = await this.fileOps.listDir(searchPath)
    return entries.filter(e => e.endsWith('.md'))
  }

  async listAllWikiFiles(): Promise<string[]> {
    const all: string[] = []
    const dirs = ['pages', '']
    for (const dir of dirs) {
      try {
        const path = this.resolvePath(dir)
        const entries = await this.fileOps.listDir(path)
        for (const e of entries) {
          if (e.endsWith('.md')) {
            all.push(dir ? `${dir}/${e}` : e)
          }
        }
      } catch {
        /* skip */
      }
    }
    return all
  }

  async getTree(): Promise<WikiTreeNode[]> {
    const root: WikiTreeNode[] = []

    const wikiNode: WikiTreeNode = {
      name: 'wiki',
      path: 'wiki',
      type: 'directory',
      children: [],
    }
    const pages = await this.listPages()
    wikiNode.children = pages.map(f => ({
      name: f.split('/').pop() || f,
      path: `wiki/pages/${f}`,
      type: 'file' as const,
    }))
    root.push(wikiNode)

    const rawNode: WikiTreeNode = {
      name: 'raw',
      path: 'raw',
      type: 'directory',
      children: [],
    }
    const rawDirs = ['pdfs', 'meetings', 'audio', 'chat', 'code', 'data', 'other']
    for (const cat of rawDirs) {
      const catNode: WikiTreeNode = {
        name: cat,
        path: `raw/${cat}`,
        type: 'directory',
        children: [],
      }
      const files = await this.listRawFiles(cat)
      catNode.children = files.map(f => ({
        name: f,
        path: `raw/${cat}/${f}`,
        type: 'file' as const,
      }))
      if (rawNode.children) rawNode.children.push(catNode)
    }
    root.push(rawNode)

    const queryNode: WikiTreeNode = {
      name: 'query',
      path: 'query',
      type: 'directory',
      children: [],
    }
    const queryDirs = ['plans', 'outputs']
    for (const cat of queryDirs) {
      const catNode: WikiTreeNode = {
        name: cat,
        path: `query/${cat}`,
        type: 'directory',
        children: [],
      }
      const files = await this.listQueryFiles(cat)
      catNode.children = files.map(f => ({
        name: f,
        path: `query/${cat}/${f}`,
        type: 'file' as const,
      }))
      if (queryNode.children) queryNode.children.push(catNode)
    }
    root.push(queryNode)

    return root
  }

  async appendLog(entry: LogEntry): Promise<void> {
    const logPath = this.resolvePath('log.md')
    const line = `- **${entry.timestamp}** | ${entry.operation} | ${entry.source} — ${entry.description}\n`
    const existing = await this.fileOps.readFile(logPath)
    await this.fileOps.writeFile(logPath, existing + line)
    logger.info('WikiManager', `Log entry added: ${entry.operation} ${entry.source}`)
  }

  async getLog(): Promise<string> {
    return this.fileOps.readFile(this.resolvePath('log.md'))
  }

  async getIndex(): Promise<string> {
    return this.fileOps.readFile(this.resolvePath('index.md'))
  }

  async updateIndex(content: string): Promise<void> {
    await this.fileOps.writeFile(this.resolvePath('index.md'), content)
  }

  async searchIndex(keyword: string): Promise<string[]> {
    const index = await this.getIndex()
    const lines = index.split('\n')
    return lines
      .filter(l => l.toLowerCase().includes(keyword.toLowerCase()))
      .map(l => l.replace(/^[-*]\s*\[([^\]]+)\]\(([^)]+)\)/, '$2').trim())
  }

  async readRawFile(category: string, filename: string): Promise<string> {
    return this.fileOps.readFile(this.resolveRaw(`${category}/${filename}`))
  }

  async writeRawFile(category: string, filename: string, content: string): Promise<void> {
    const path = this.resolveRaw(`${category}/${filename}`)
    await this.fileOps.writeFile(path, content)
    logger.info('WikiManager', `Raw file saved: ${category}/${filename}`)
  }

  async deleteRawFile(category: string, filename: string): Promise<void> {
    const path = this.resolveRaw(`${category}/${filename}`)
    if (this.fileOps.deleteFile) {
      await this.fileOps.deleteFile(path)
    } else {
      await this.fileOps.writeFile(path, '')
    }
  }

  async listRawFiles(category?: string): Promise<string[]> {
    const path = category ? this.resolveRaw(category) : this.resolveRaw('')
    try {
      return await this.fileOps.listDir(path)
    } catch {
      return []
    }
  }

  async getAllRawFiles(): Promise<RawFileInfo[]> {
    const result: RawFileInfo[] = []
    const categories = ['pdfs', 'meetings', 'audio', 'chat', 'code', 'data', 'other']
    for (const cat of categories) {
      const files = await this.listRawFiles(cat)
      for (const f of files) {
        result.push({
          name: f,
          path: `raw/${cat}/${f}`,
          type: cat === 'pdfs' ? 'pdf' : cat === 'meetings' ? 'meeting' : cat as RawFileInfo['type'],
          size: 0,
          importedAt: new Date().toISOString(),
          ingested: false,
        })
      }
    }
    return result
  }

  async writeQueryPlan(queryId: string, content: string): Promise<void> {
    const path = this.resolveQuery(`plans/${queryId}.md`)
    await this.fileOps.writeFile(path, content)
  }

  async writeQueryOutput(queryId: string, content: string): Promise<void> {
    const path = this.resolveQuery(`outputs/${queryId}.md`)
    await this.fileOps.writeFile(path, content)
  }

  async readQueryPlan(queryId: string): Promise<string> {
    return this.fileOps.readFile(this.resolveQuery(`plans/${queryId}.md`))
  }

  async readQueryOutput(queryId: string): Promise<string> {
    return this.fileOps.readFile(this.resolveQuery(`outputs/${queryId}.md`))
  }

  async listQueryFiles(category?: string): Promise<string[]> {
    const path = category ? this.resolveQuery(category) : this.resolveQuery('')
    try {
      const entries = await this.fileOps.listDir(path)
      return entries.filter(e => e.endsWith('.md'))
    } catch {
      return []
    }
  }

  async readFile(path: string): Promise<string> {
    return this.fileOps.readFile(path)
  }

  async clearAll(): Promise<void> {
    const sections = [
      { base: WIKI_BASE, dirs: ['pages', ''] },
      { base: RAW_BASE, dirs: ['pdfs', 'meetings', 'audio', 'chat', 'code', 'data', 'other'] },
      { base: QUERY_BASE, dirs: ['plans', 'outputs'] },
    ]
    for (const section of sections) {
      for (const dir of section.dirs) {
        const path = dir ? `${section.base}/${dir}` : section.base
        try {
          const files = await this.fileOps.listDir(path)
          for (const f of files) {
            const fullPath = `${path}/${f}`
            if (this.fileOps.deleteFile) {
              await this.fileOps.deleteFile(fullPath)
            }
          }
        } catch {
          /* skip */
        }
      }
    }
    await this.init()
    logger.info('WikiManager', 'All wiki, raw, and query data cleared')
  }

  private parseMeta(content: string, path: string): PageMeta {
    const titleMatch = content.match(/^#\s+(.+)/m)
    const tagsMatch = content.match(/^tags:\s*(.+)$/m)
    const cat = path.startsWith('wiki/') ? 'page' : path.split('/')[0]
    return {
      title: titleMatch?.[1] || path.split('/').pop()?.replace('.md', '') || path,
      path,
      category: (cat as PageMeta['category']) || 'page',
      created: '',
      updated: new Date().toISOString(),
      tags: tagsMatch?.[1]?.split(',').map(t => t.trim()) || [],
    }
  }
}
