name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: false
          VALIDATE_KOTLIN: false
          VALIDATE_PYTHON: false
          VALIDATE_GO: false
          VALIDATE_RUST: false
          VALIDATE_RUBY: false
          VALIDATE_PHP: false
          VALIDATE_XML: false
          VALIDATE_PROPERTIES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
